SELECT * FROM "UZYTKOWNIK" JOIN  "EKSPERYMENTY_DOSTEP" ON (id_uzytkownika = "UZYTKOWNIK".id) 
JOIN "SESJA_POMIAROWA" ON (sesja_id = "SESJA_POMIAROWA".id) 
JOIN "EKSPERYMENT" ON ("EKSPERYMENT".id = nazwa_id);
